v3.13

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -146,7 +146,7 @@ fi
 
 
 AC_CHECK_FUNCS(select fcntl uname nice setpriority getcwd getwd putenv)
-AC_CHECK_FUNCS(sigaction syslog)
+AC_CHECK_FUNCS(sigaction syslog realpath)
 
 AC_CHECK_HEADERS(unistd.h crypt.h sys/select.h)
 
@@ -456,6 +456,7 @@ case "$host" in
     # On HPUX 10.x, the parts of X that HP considers "standard" live in
     # /usr/{include,lib}/X11R6/.  The parts that HP doesn't consider
     # "standard", notably, Xaw and Xmu, live in /usr/contrib/X11R6/.
+    # Yet /usr/contrib/X11R6/ comes preinstalled on all HPUX systems.
     # Also, there are symlinks from /usr/include/ and /usr/lib/ into
     # /usr/{include,lib}/X11R6/, so that (if you don't use Xmu at all)
     # you don't need any -I or -L arguments.
@@ -477,10 +478,7 @@ case "$host" in
     # that are available.  We do not mix and match different versions
     # of X.
     #
-    # Questions I still don't know the answers to: (do you?)
-    #
-    #   * Does HPUX 10.x come with /usr/contrib/X11R6/ standard?  
-    #     Or does that need to be installed separately?
+    # Question I still don't know the answer to: (do you?)
     #
     #   * On HPUX 9.x, where /usr/include/X11R5/ was standard, and
     #     /usr/contrib/X11R6/ could be installed as a patch, what was in
@@ -575,7 +573,10 @@ else
   XMU_OBJS=''
   SAVER_LIBS="-lXmu $SAVER_LIBS"
   HACK_LIBS="-lXmu $HACK_LIBS"
-  TOOLKIT_LIBS="-lXmu $TOOLKIT_LIBS"
+  MOTIF_LIBS="-lXmu $MOTIF_LIBS"
+  GTK_LIBS="-lXmu $GTK_LIBS"
+  ATHENA_LIBS="-lXmu $ATHENA_LIBS"
+  ATHENA3D_LIBS="-lXmu $ATHENA3D_LIBS"
   AC_DEFINE(HAVE_XMU)
 fi
 
@@ -949,9 +950,11 @@ fi
 # Check for Motif and Athena --with and --without arguments.
 #
 have_motif=no
+have_gtk=no
 have_athena=no
 have_athena3d=no
 with_motif_req=unspecified
+with_gtk_req=unspecified
 with_athena_req=unspecified
 
 AC_ARG_WITH(motif,[
@@ -964,6 +967,14 @@ X Client Toolkit options:
 
 HANDLE_X_PATH_ARG(with_motif, --with-motif, Motif)
 
+AC_ARG_WITH(gtk,
+[  --with-gtk              Use the Gtk toolkit for the user interface, if
+                          possible (this is the default).
+  --without-gtk           Do not use Gtk.],
+  [with_gtk="$withval"; with_gtk_req="$withval"],[with_gtk=no])
+
+HANDLE_X_PATH_ARG(with_gtk, --with-gtk, Gtk)
+
 AC_ARG_WITH(athena,
 [  --with-athena           Use the Athena toolkit for the user interface, if
                           possible (this is the default if Motif isn't used.)
@@ -972,8 +983,14 @@ AC_ARG_WITH(athena,
 
 HANDLE_X_PATH_ARG(with_athena, --with-athena, Athena)
 
+
 if test "$with_motif" != yes -a "$with_motif" != no ; then
   echo "error: must be yes or no: --with-motif=$with_motif"
+  exit 1
+fi
+
+if test "$with_gtk" != yes -a "$with_gtk" != no ; then
+  echo "error: must be yes or no: --with-gtk=$with_gtk"
   exit 1
 fi
 
@@ -983,85 +1000,36 @@ if test "$with_athena" != yes -a "$with_athena" != no ; then
 fi
 
 
-# Saying --without-motif is the same as saying --with-athena.
-if test "$with_motif_req" = no ; then
-  with_athena_req=yes
-  with_athena=yes
+AC_CHECK_X_HEADER(Xm/Xm.h,
+		  [have_motif=yes
+		   AC_DEFINE(HAVE_MOTIF)
+		   MOTIF_LIBS="$MOTIF_LIBS -lXm"])
+
+AC_CHECK_PROGS(glib_config, glib-config)
+AC_CHECK_PROGS(gtk_config, gtk-config)
+if test -n "$glib_config" -a  -n "gtk_config" ; then
+  INCLUDES="$INCLUDES `$gtk_config --cflags`"
+  GTK_LIBS="$GTK_LIBS `$gtk_config --libs`"
+  AC_DEFINE(HAVE_GTK)
+  have_gtk=yes
 fi
 
-# Saying --without-athena is the same as saying --with-motif.
-if test "$with_athena_req" = no ; then
-  with_motif_req=yes
-  with_motif=yes
+AC_CHECK_X_HEADER(X11/Xaw/Dialog.h, [have_athena=yes])
+if test "$have_athena" = yes; then
+  AC_CHECK_X_LIB(Xaw3d, Xaw3dComputeTopShadowRGB,
+                [have_athena=yes; have_athena3d=yes], [],
+		-lXt -lXmu -lXext -lX11)
 fi
 
-# Check for Motif and Athena headers.
-
-check_motif() {
-  AC_CHECK_X_HEADER(Xm/Xm.h,
-		    [have_motif=yes
-		     AC_DEFINE(HAVE_MOTIF)
-		     TOOLKIT_LIBS="-lXm $TOOLKIT_LIBS"])
-}
-
-check_athena() {
-  have_athena=no
-  have_athena3d=no
-  AC_CHECK_X_HEADER(X11/Xaw/Dialog.h, [have_athena=yes])
-  if test "$have_athena" = yes; then
-    AC_CHECK_X_LIB(Xaw3d, Xaw3dComputeTopShadowRGB,
-		   [have_athena=yes; have_athena3d=yes], [],
-		   -lXt -lXmu -lXext -lX11)
-  fi
-
-  if test "$have_athena3d" = yes; then
-    TOOLKIT_LIBS="-lXaw3d $TOOLKIT_LIBS"
-  elif test "$have_athena" = yes; then
-    TOOLKIT_LIBS="-lXaw $TOOLKIT_LIBS"
-  fi
-}
-
-
-# If they asked for both motif and athena, check motif then athena.
-# If they asked for only motif, check motif then athena.
-# If they asked for only athena, check athena then motif.
-# If they asked for neither, check motif then athena.
-
-proselytize_motif=yes
-if test "$with_motif" = yes; then
-  # asked for both, or for motif only
-  check_motif
-  if test "$have_motif" = yes; then
-    with_athena=no
-    with_athena_req=no
-  else
-    check_athena
-  fi
-
-elif test "$with_athena" = yes; then
-  # asked for athena only
-  check_athena
-  if test "$have_athena" = yes; then
-    with_motif=no
-    proselytize_motif=no
-  else
-    check_motif
-  fi
-
-else
-  # asked for neither
-  check_motif
-  if test "$have_motif" = yes; then
-    with_athena=no
-  else
-    check_athena
-  fi
-
+if test "$have_athena" = yes; then
+  AC_DEFINE(HAVE_ATHENA)
+  ATHENA_LIBS="-lXaw $ATHENA_LIBS"
 fi
 
-if test "$have_motif" = yes; then
-  proselytize_motif=no
+if test "$have_athena3d" = yes; then
+  ATHENA3D_LIBS="-lXaw3d $ATHENA3D_LIBS"
 fi
+
 
 # If we have Athena, check whether it's a version that includes
 # XawViewportSetCoordinates in Viewport.h (R3 (or R4?) don't.)
@@ -1168,7 +1136,8 @@ fi
 motif_requires_xpm=no
 if test "$have_motif" = yes ; then
    AC_MSG_CHECKING(whether Motif requires XPM)
-   if test "$motif_version" -ge 2000; then
+   if test "$motif_version" = "unknown" || test "$motif_version" -ge 2000
+   then
      motif_requires_xpm=yes
      AC_MSG_RESULT(maybe)
    else
@@ -1186,7 +1155,7 @@ have_xp_ext=no
 if test "$have_motif" = yes ; then
    have_xp_ext=no
    AC_CHECK_X_LIB(Xp, XpQueryExtension,
-		  [have_xp_ext=yes; TOOLKIT_LIBS="$TOOLKIT_LIBS -lXp"],
+		  [have_xp_ext=yes; MOTIF_LIBS="$MOTIF_LIBS -lXp"],
 		  [], -lX11 -lXext -lm)
 fi
 
@@ -1199,7 +1168,7 @@ if test "$have_motif" = yes ; then
   AC_CHECK_X_LIB(Xintl, _Xsetlocale, [have_xintl=yes], [have_xintl=no],
                  -lX11 -lXext -lm)
   if test "$have_xintl" = yes; then
-    TOOLKIT_LIBS="$TOOLKIT_LIBS -lXintl"
+    MOTIF_LIBS="$MOTIF_LIBS -lXintl"
   fi
 fi
 
@@ -1233,7 +1202,7 @@ fi
 #
 if test "$have_motif" = yes -a "$have_xpm" = yes ; then
   if test "$motif_requires_xpm" = yes ; then
-    TOOLKIT_LIBS="$TOOLKIT_LIBS $XPM_LIBS"
+    MOTIF_LIBS="$MOTIF_LIBS $XPM_LIBS"
   fi
 fi
 
@@ -1724,8 +1693,11 @@ if test "$enable_locking" = yes; then
     if test "$ac_cv_pam" = yes ; then
 	  have_pam=yes
 	  AC_DEFINE(HAVE_PAM)
-	  PASSWD_LIBS="${PASSWD_LIBS} -lpam -ldl"
+	  PASSWD_LIBS="${PASSWD_LIBS} -lpam"
 
+          # libpam typically requires dlopen and dlsym.  On FreeBSD,
+          # those are in libc.  On Linux and Solaris, they're in libdl.
+          AC_CHECK_LIB(dl, dlopen, [PASSWD_LIBS="${PASSWD_LIBS} -ldl"])
 
           AC_MSG_CHECKING(how to call pam_strerror)
           AC_CACHE_VAL(ac_cv_pam_strerror_args,
@@ -2021,7 +1993,7 @@ fi
 
 
 if test \! -z "$includedir" ; then 
-  INCLUDES="-I$includedir"
+  INCLUDES="$INCLUDES -I$includedir"
 fi
 
 if test \! -z "$libdir" ; then
@@ -2037,18 +2009,24 @@ DEPEND_DEFINES=
 
 # Done testing things -- now substitute in some stuff for the Makefiles.
 #
-if test "$have_motif" = yes; then
-  AC_DEFINE(HAVE_MOTIF)
-  TOOLKIT_SRCS='$(MOTIF_SRCS)'
-  TOOLKIT_OBJS='$(MOTIF_OBJS)'
-elif test "$have_athena" = yes; then
-  AC_DEFINE(HAVE_ATHENA)
-  TOOLKIT_SRCS='$(ATHENA_SRCS)'
-  TOOLKIT_OBJS='$(ATHENA_OBJS)'
-else
-  TOOLKIT_SRCS=''
-  TOOLKIT_OBJS=''
+ALL_DEMO_PROGRAMS=
+if test "$have_athena3d" = yes; then
+  PREFERRED_DEMO_PROGRAM=xscreensaver-demo-Xaw3d
+  ALL_DEMO_PROGRAMS="$PREFERRED_DEMO_PROGRAM $ALL_DEMO_PROGRAMS"
 fi
+if test "$have_athena" = yes; then
+  PREFERRED_DEMO_PROGRAM=xscreensaver-demo-Xaw
+  ALL_DEMO_PROGRAMS="$PREFERRED_DEMO_PROGRAM $ALL_DEMO_PROGRAMS"
+fi
+if test "$have_gtk" = yes; then
+  PREFERRED_DEMO_PROGRAM=xscreensaver-demo-Gtk
+  ALL_DEMO_PROGRAMS="$PREFERRED_DEMO_PROGRAM $ALL_DEMO_PROGRAMS"
+fi
+if test "$have_motif" = yes; then
+  PREFERRED_DEMO_PROGRAM=xscreensaver-demo-Xm
+  ALL_DEMO_PROGRAMS="$PREFERRED_DEMO_PROGRAM $ALL_DEMO_PROGRAMS"
+fi
+
 
 if test "$have_kerberos" = yes; then
   PASSWD_SRCS="$PASSWD_SRCS \$(KERBEROS_SRCS)"
@@ -2090,8 +2068,13 @@ fi
 
 AC_SUBST(INCLUDES)
 
+AC_SUBST(PREFERRED_DEMO_PROGRAM)
+AC_SUBST(ALL_DEMO_PROGRAMS)
 AC_SUBST(SAVER_LIBS)
-AC_SUBST(TOOLKIT_LIBS)
+AC_SUBST(MOTIF_LIBS)
+AC_SUBST(GTK_LIBS)
+AC_SUBST(ATHENA_LIBS)
+AC_SUBST(ATHENA3D_LIBS)
 AC_SUBST(HACK_LIBS)
 AC_SUBST(XPM_LIBS)
 AC_SUBST(GL_LIBS)
@@ -2103,8 +2086,6 @@ AC_SUBST(INSTALL_PAM)
 AC_SUBST(SGI_VIDEO_OBJS)
 AC_SUBST(SGI_VIDEO_LIBS)
 
-AC_SUBST(TOOLKIT_SRCS)
-AC_SUBST(TOOLKIT_OBJS)
 AC_SUBST(PASSWD_SRCS)
 AC_SUBST(PASSWD_OBJS)
 AC_SUBST(XMU_SRCS)
@@ -2205,19 +2186,42 @@ if test "$with_xf86vmode_req" = yes -a "$have_xf86vmode" = no ; then
   warn 'The XF86VMODE extension was requested, but was not found.'
 fi
 
-if test "$have_motif" = no -a "$have_athena" = no ; then
-  warnL "Neither Motif nor Athena widgets seem to be available;"
-  warn2 "the \`xscreensaver-demo' program requires one or the"
-  warn2 "other."
+
+if test "$have_motif" = no -a "$have_gtk" = no; then
+  proselytize_motif=yes
+else
+  proselytize_motif=no
+fi
+
+
+if test "$have_motif" = no -a "$have_gtk" = no -a "$have_athena" = no ; then
+  warnL "None of Motif, Gtk, or Athena widgets seem to be available;"
+  warn2 "the \`xscreensaver-demo' program requires one of these."
   proselytize_motif=no
 
 elif test "$with_motif_req" = yes -a "$have_motif" = no ; then
   warnL "Use of Motif was requested, but it wasn't found;"
-  warn2 "Athena will be used instead."
+  if test "$have_gtk" = yes; then
+    warn2 "Gtk will be used instead."
+  else
+    warn2 "Athena will be used instead."
+  fi
+
+elif test "$with_gtk_req" = yes -a "$have_gtk" = no ; then
+  warnL "Use of Gtk was requested, but it wasn't found;"
+  if test "$have_motif" = yes; then
+    warn2 "Motif will be used instead."
+  else
+    warn2 "Athena will be used instead."
+  fi
 
 elif test "$with_athena_req" = yes -a "$have_athena" = no ; then
   warnL "Use of Athena was requested, but it wasn't found;"
-  warn2 "Motif will be used instead."
+  if test "$have_gtk" = yes; then
+    warn2 "Gtk will be used instead."
+  else
+    warn2 "Motif will be used instead."
+  fi
 fi
 
 if test "$have_motif" = yes -a "$have_lesstif" = yes ; then
@@ -2239,12 +2243,13 @@ if test "$have_motif" = yes -a "$have_lesstif" = yes ; then
 fi
 
 if test "$proselytize_motif" = yes ; then
-    warnL "Athena widgets are being used instead of Motif."
+    warnL "Athena widgets are being used instead of Motif or Gtk."
     warn2 "The \`xscreensaver-demo' program looks much better"
-    warn2 "with Motif.  Wouldn't you rather be using Motif?"
-    warn2 "It is shipped by every commercial Unix vendor;"
+    warn2 "with Motif or Gtk.  Wouldn't you rather be using Motif?"
+    warn2 "Motif is shipped by every commercial Unix vendor,"
     warn2 "and there is a free implementation available as"
-    warn2 "well: see <http://www.lesstif.org/>."
+    warn2 "well: see <http://www.lesstif.org/>.  Gtk is shipped"
+    warn2 "with most Linux and BSD distributions."
 fi
 
 
